[PHP]
max_execution_time = 300
memory_limit = 128M
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
post_max_size = 50M
upload_max_filesize = 50M
default_charset = "UTF-8"

extension_dir = "ext"

extension=curl
extension=mbstring
extension=openssl
extension=pdo_sqlite
extension=sqlite3

[Date]
date.timezone = "Asia/Kolkata"